# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductCatalogApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='Product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='visiblity',
            new_name='visibility',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'products/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
    ]
