# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-02 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductCatalogApp', '0002_auto_20170630_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'media/products/'),
        ),
    ]
